version: '3'

services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - miniostorage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel
    volumes:
      - ./files/cloudflared:/etc/cloudflared

volumes:
  miniostorage:
