ingress:
  - hostname: minio.$TUNNEL_HOSTNAME
    service: http://minio:9000
    originRequest:
      httpHostHeader: minio.$TUNNEL_HOSTNAME
  - hostname: minioconsole.$TUNNEL_HOSTNAME
    service: http://minio:9001
    originRequest:
      httpHostHeader: minioconsole.$TUNNEL_HOSTNAME
  - service: http_status:404
